### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#10]
## Description
Create the hero section with an animation that displays logo in the center. When scrolling down, the logo should move to the navbar

## Tasks
- [ ] Develop the hero section layout**
- [ ] Implement the logo animation***
- [ ] Test responsiveness for different screen sizes

** Ensure navigation bar has been implemented before starting
*** [Codepen](https://codepen.io/tutsplus/pen/wvQEyJE) for reference: something similar but navbar is on top
