### ISSUE TITLE
Events Section

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#11]
## Description
Create an events section that displays upcoming events in a card-based layout with a slider control (carousel). Each card should have the information as outlined in the design specs.

## Tasks
- [ ] Design the layout
- [ ] Create the card component
- [ ] Implement the carousel**
- [ ] Add hover/transition effects

** Use libraries to make things easier
