### ISSUE TITLE
Newsfeed Section

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#12]
## Description
Create a newsfeed section that displays articles or updates in a grid layout with cards for each article. 

## Tasks
- [x] Design the newsfeed layout using grids
- [x] Create the article component
- [x] Add hover/transition effects
- [x] Test grid responsiveness on different screens
