### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#13]
## Description
Create a footer that includes social links, and an input field to sign up for the newsletter.

## Tasks
- [x] Develop footer layout
- [x] Include links to social media/contacts
- [x] Create input field for sign ups
