### ISSUE TITLE
Event Details Page

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#31]
## Description
Create an events details page that opens once user clicks on an event in the events section. This page includes more details about the event and has a registration form to sign up for events.

## Tasks
- [x] Create the details page and route on event clicked
- [x] Create the layout and style the page
- [x] Implement the form with animation**
- [x] Add regex for email and student ID
- [x] Error handling for form

** The second input field style in this [codepen](https://codepen.io/beforesemicolon/pen/VwaWagB?editors=1100)
