### ISSUE TITLE
Event Section Rendering

### ISSUE THREAD

**Issue by rudyx3** [UOWD-Tech-Club/Tech-Club-Website#34]
### **Description**
Show all the upcoming events in the events section from the database.

### **Tasks**
- [ ] Make a function to request the backend server to fetch the events
- [ ] Display the events in the event carousel
- [ ] Storing images in the Database as links and fetch images

**Comment by rudyx3** [comment]
Finished the mentioned tasks.
