### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by hybachi** [UOWD-Tech-Club/Tech-Club-Website#9]
## Description
Create a responsive navigation bar that includes links to different pages (check design specs) and should be sticky with the logo on the left side.

## Tasks
- [x] Implement the navbar using flexbox**
- [x] Set up routes to different pages
- [x] Include the toggle menu for mobile nav

** Task required for Hero Section development so merge into main before attempting other tasks (do not close issue)
